# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '17_Firebase_dbozer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 17_Firebase_dbozer
	pod 'Firebase/Auth'
	pod 'Firebase/Database'

end
